// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gamem

const TableNameTbSumOrderGame = "tb_sum_order_game"

// TbSumOrderGame 游戏报表
type TbSumOrderGame struct {
	ID                        int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GameType                  int64   `gorm:"column:game_type;not null;comment:游戏类型" json:"game_type"`              // 游戏类型
	GameName                  string  `gorm:"column:game_name;not null;comment:游戏名称" json:"game_name"`              // 游戏名称
	Currency                  string  `gorm:"column:currency;not null;comment:币种" json:"currency"`                  // 币种
	Amount                    int64   `gorm:"column:amount;not null;comment:投注金额" json:"amount"`                    // 投注金额
	ProfitAmount              int64   `gorm:"column:profit_amount;not null;comment:中奖金额" json:"profit_amount"`      // 中奖金额
	ValidBet                  int64   `gorm:"column:valid_bet;comment:有效" json:"valid_bet"`                         // 有效
	PrizeAmount               int64   `gorm:"column:prize_amount;not null;comment:派奖金额" json:"prize_amount"`        // 派奖金额
	AwardAmount               int64   `gorm:"column:award_amount;not null;comment:派奖金额" json:"award_amount"`        // 派奖金额
	ProfitRate                string  `gorm:"column:profit_rate;not null;default:0;comment:盈利率" json:"profit_rate"` // 盈利率
	BetContentProfitableColor string  `gorm:"column:bet_content_profitable_color;not null" json:"bet_content_profitable_color"`
	BetCount                  int64   `gorm:"column:bet_count;comment:投注数量" json:"bet_count"`                                                    // 投注数量
	BetUsers                  int64   `gorm:"column:bet_users;comment:投注人数" json:"bet_users"`                                                    // 投注人数
	PoolMoney                 string  `gorm:"column:pool_money;not null;comment:奖池贡献" json:"pool_money"`                                         // 奖池贡献
	CreatedAt                 int64   `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                  // 创建时间
	UpdatedAt                 int64   `gorm:"column:updated_at;comment:更新时间-订单取消的时候用" json:"updated_at"`                                         // 更新时间-订单取消的时候用
	OrderAt                   int64   `gorm:"column:order_at;comment:下单时间" json:"order_at"`                                                      // 下单时间
	GiftPrice                 int64   `gorm:"column:gift_price;not null;comment:小费" json:"gift_price"`                                           // 小费
	RoundNum                  int64   `gorm:"column:round_num;comment:局数" json:"round_num"`                                                      // 局数
	GameCode                  string  `gorm:"column:game_code;comment:游戏代码" json:"game_code"`                                                    // 游戏代码
	JackpotAmount             float64 `gorm:"column:jackpot_amount;not null;default:0.0000;comment:Jackpot amount / 奖池金额" json:"jackpot_amount"` // Jackpot amount / 奖池金额
}

// TableName TbSumOrderGame's table name
func (*TbSumOrderGame) TableName() string {
	return TableNameTbSumOrderGame
}
